---
- name: testing windows
  hosts: 10.10.5.187
  tasks:
     - name: install windows exporter
       win_shell: |
         wget https://github.com/prometheus-community/windows_exporter/releases/download/v0.22.0/windows_exporter-0.22.0-amd64.exe -o windows_exporter-0.22.0-amd64.exe
         Start-Process C:\Users\CREDENCE\Downloads\windows_exporter-0.22.0-386.exe -PassThru
         service.msc start windows_exporter
