---
- name: testing windows
  hosts: 10.10.5.187
  #gather_facts: false
  become_user: credence
  become: true
  
  tasks:
  # - name: Install git
  #   win_chocolatey:
  #      name: git
  #      state: present
   - name: download java bin
     win_get_url:
         url: https://download.oracle.com/java/20/latest/jdk-20_windows-x64_bin.exe
         dest: C:\Users\credence2\Documents\
...
