---
- name: testing windows
  hosts: 10.10.5.187
  #gather_facts: false
  become_user: credence
  become: true
  
  tasks:
   - name: Install git
     win_chocolatey:
        name: git
        state: present
   - name: Install Tomcat with Chocolatey
     win_chocolatey:
         name: tomcat
         state: present
         version: '8.5.12'
