---
- name: testing windows
  hosts: 10.10.5.193
  #gather_facts: false
  become_user: inndata-kap-3
  become: true
  
  tasks:
   - name: test create dir
     win_file:
        path: C:\Users\inndata-kap-3\sample-data
        state: directory
...  
