---
- name: testing windows
  hosts: 10.10.5.187
  #gather_facts: false
  become_user: credence
  become: true
  
  tasks:
  # - name: Install git
  #   win_chocolatey:
  #      name: git
  #      state: present
   - name: download java bin
     win_get_url:
         url: https://download.oracle.com/java/20/latest/jdk-20_windows-x64_bin.exe
         dest: C:\Users\credence2\Documents\
     #    force: true
   - name: install java
     win_environment:
       state: present
       name: JAVA_HOME
       value: 'C:\Program Files\Java\jdk-20'
       level: machine
   - name: Add Java to path
     win_path:
        elements:
          - 'C:\Program Files\Java\jdk-20\bin'
    # win_shell: |
     #    cd C:\Users\credence2\Documents\
      #   .\jdk-20_windows-x64_bin.exe
...
