---
- name: testing windows
  hosts: 10.10.5.187
  #gather_facts: false
  become_user: credence
  become: true
  
  tasks:
   - name: un Install git
     win_chocolatey:
        name: git
        state: absent
