---
- name: testing windows
  hosts: 10.10.5.187
  #gather_facts: false
  become_user: credence
  become: true
  
  tasks:
   - name: Install git
     win_chocolatey:
        name: git
        state: present
   - name: Install Java
     win_chocolatey:
       name: jdk11
       state: present
       version: 11
