---
- name: testing windows
  hosts: all
  #gather_facts: false
  #become_user: inndata-kap-5
  #become: true
  
  tasks:
   - name: test create dir
     win_file:
        path: C:\Users\sample-data
        state: directory
...  
