---
- name: testing windows
  hosts: windows-win
  become_user: credence2
  become: true
  
  tasks:
    - name: create dir
      win_file:
            path: C:\Users\credence2\Documents\sample
            state: directory
...
