---
- name: testing windows
  hosts: 10.10.5.185
  gather_facts: no

  tasks:

    - name: Copy file from Unix server to Windows 10 machine
      win_copy:
        src: /sftp-data/mysftp/sftp-upload/Ping
        dest: C:\kapalya-drivers
      delegate_to: "{{ ansible_ssh_host }}"
      become: yes
      become_user: mysftp
  vars:
    ansible_ssh_host: 10.10.5.76
    ansible_ssh_user: mysftp
    ansible_ssh_pass: 123456

 #    - name: create dir for loading drivers
 #      win_file:
 #         path: C:\kapalya-drivers
 #         state: directory
 #    - name: Transfer files via SFTP
 #      expect:
 #        command: sftp mysftp@10.10.5.76
 #        responses:
 #          "(yes/no)?": "yes\n"
 #          "password: ": "123456\n"
 #        timeout: 30
 #        echo: yes
 #        spawn: yes
 #        commands:
 #          - "mget -r /sftp-upload/Ping/Replicadb C:\\kapalya-drivers"
 #          - "\exit"
 # win_command: "winscp /command \"open sftp://mysftp@10.10.5.76\" \"get /sftp-upload/Ping/Replicadb C:\\kapalya-drivers\" \"exit\""
