---
- name: testing windows
  hosts: 10.10.5.187
  #gather_facts: false
  become_user: credence
  become: true
  
  tasks:
    - name: create dir
      win_file:
            path: C:\Users\credence2\Documents\sample
            state: directory
...
