---
- name: Run Windows execute.cmd file
  hosts: 10.10.5.185
  become_method: runas
  vars:
    ansible_become_password: 1qaz2wsx
  tasks:
    - name: Execute .cmd file with password
      win_shell: "C:\\Users\\inndata-dat-005\\Just\\ARC\\execute.cmd"
      become: yes
      become_user: Administrator
      become_password: 1qaz2wsx
# ---
# - hosts: 10.10.5.185
#   tasks:
#     - name: "This should create a bucket"
#       minio_bucket:
#         s3_url: https://10.10.5.76:9001
#         name: test-bucket
#         access_key: admin
#         secret_key: gqfxQz1AiAm
#         state: present
#         policy: read-only
# ---
# - name: Copy file from Unix server to Windows server
#   hosts: 10.10.5.185
#   gather_facts: no
#   tasks:
#      - name: Transfer files via SFTP
#        expect:
#          command: sftp mysftp@10.10.5.76
#          responses:
#            # "(yes/no)?": "yes\n"
#            "password": "123456\n"
#          timeout: 30
#          echo: yes
#          spawn: yes
#          commands:
#            - "mget -r /sftp-upload/Ping/Replicadb C:\\\\kapalya-drivers\\\\"
#            - "exit"
