---
- name: testing windows
  hosts: 10.10.5.192
  tasks:
   - win_shell: install-packageprovider -name nuget -force
   - name: "Install GroupPolicyDSC"
     win_psmodule:
        name: GroupPolicyDSC
        state: present
   - name: "Create GPO"
     win_dsc:
        resource_name: GroupPolicy
        name: "ExampleGPO"
        status: allsettingsenabled
        ensure: present
