---
- name: Run Windows execute.cmd file
  hosts: 10.10.5.185
  become_method: runas
  become: yes
  become_user: Administrator
  vars:
    ansible_become_password: 1qaz2wsx
  tasks:
    - name: Execute command to suppress UAC prompt
      win_shell: |
        $command = "C:\Users\inndata-dat-005\Just\ARC\execute.cmd /s /q"
        $processInfo = New-Object System.Diagnostics.ProcessStartInfo
        $processInfo.FileName = $command
        $processInfo.UseShellExecute = $false
        $processInfo.RedirectStandardOutput = $true
        $process = [System.Diagnostics.Process]::Start($processInfo)
        $process.WaitForExit()
      become: yes
      register: result
      # ignore_errors: yes  # Ignore any errors during execution

    - name: Display command output (optional)
      debug:
        var: result.stdout_lines

  # tasks:
  #   - name: check connection
  #     win_ping:
        # win_file: 
        #    path: C:\\admintesting
        #    state: directory
  # tasks:
  #   - name: Execute command to suppress UAC prompt
  #     win_shell: |
  #       $command = "C:\Users\inndata-dat-005\Just\ARC\execute.cmd"
  #       $processInfo = New-Object System.Diagnostics.ProcessStartInfo
  #       $processInfo.FileName = $command
  #       $processInfo.UseShellExecute = $false
  #       $processInfo.RedirectStandardOutput = $true
  #       $process = [System.Diagnostics.Process]::Start($processInfo)
  #       $process.WaitForExit()
  #     register: result
  #     ignore_errors: yes  # Ignore any errors during execution

  #   - name: Display command output (optional)
  #     debug:
  #       var: result.stdout_lines
  # tasks:
  #   - name: Execute .cmd file with password
  #     win_command: "C:\\Users\\inndata-dat-005\\Just\\ARC\\execute.cmd /silent"
# ---
# - hosts: 10.10.5.185
#   tasks:
#     - name: "This should create a bucket"
#       minio_bucket:
#         s3_url: https://10.10.5.76:9001
#         name: test-bucket
#         access_key: admin
#         secret_key: gqfxQz1AiAm
#         state: present
#         policy: read-only
# ---
# - name: Copy file from Unix server to Windows server
#   hosts: 10.10.5.185
#   gather_facts: no
#   tasks:
#      - name: Transfer files via SFTP
#        expect:
#          command: sftp mysftp@10.10.5.76
#          responses:
#            # "(yes/no)?": "yes\n"
#            "password": "123456\n"
#          timeout: 30
#          echo: yes
#          spawn: yes
#          commands:
#            - "mget -r /sftp-upload/Ping/Replicadb C:\\\\kapalya-drivers\\\\"
#            - "exit"
