---
- name: Run Windows execute.cmd file
  hosts: 10.10.5.185
  # become: yes
  # vars:
  #   ansible_become_method: runas
  #   ansible_become_user: Administrator
  #   ansible_become_password: 1qaz2wsx
  tasks:
    - name: Execute .cmd file with password
      win_shell: C:\Users\inndata-dat-005\Just\ARC\execute.bat
        # path: C:\Users\inndata-dat-005\Just\ARC\execute.bat
        # _raw_params: C:\Users\inndata-dat-005\Just\ARC\execute.bat

      async: 5
      poll: 0
      register: cmd_result

    - name: Wait for the task to complete (max 5 seconds)
      async_status:
        jid: "{{ cmd_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 1
      delay: 0
      ignore_errors: true

    - name: Display task result
      debug:
        var: cmd_result
      
  # tasks:
  #   - name: check connection
  #     win_ping:
        # win_file: 
        #    path: C:\\admintesting
        #    state: directory
        
#   tasks:
    # - name: "This should create a bucket"
    #   minio_bucket:
    #     s3_url: https://10.10.5.76:9001
    #     name: test-bucket
    #     access_key: DW1v3EfdBLR0J1GVhdjC
    #     secret_key: 5VytN79seVFxeYmAmwLlYUF4O0rp0Hlnex50GyTf
    #     state: present
    #     policy: read-only
# ---
# - name: Copy file from Unix server to Windows server
#   hosts: 10.10.5.185
#   gather_facts: no
#   tasks:
#      - name: Transfer files via SFTP
#        expect:
#          command: sftp mysftp@10.10.5.76
#          responses:
#            # "(yes/no)?": "yes\n"
#            "password": "123456\n"
#          timeout: 30
#          echo: yes
#          spawn: yes
#          commands:
#            - "mget -r /sftp-upload/Ping/Replicadb C:\\\\kapalya-drivers\\\\"
#            - "exit"
